insert into seller (idSeller, name, lastName, address, telephone, email) values (1, 'Michel', 'Leyburn', '018 Graceland Circle', '0963255773', 'mleyburn0@alexa.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (2, 'Eleni', 'Bendik', '49 Grayhawk Park', '0935768155', 'ebendik1@buzzfeed.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (3, 'Layla', 'Mayall', '42 Superior Junction', '0945219724', 'lmayall2@thetimes.co.uk');
insert into seller (idSeller, name, lastName, address, telephone, email) values (4, 'Alisha', 'Grimshaw', '5329 Schlimgen Circle', '0902475869', 'agrimshaw3@i2i.jp');
insert into seller (idSeller, name, lastName, address, telephone, email) values (5, 'Keane', 'Chasmer', '613 Aberg Court', '0985334073', 'kchasmer4@hostgator.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (6, 'Evyn', 'Cornick', '415 Dwight Way', '0956644377', 'ecornick5@tuttocitta.it');
insert into seller (idSeller, name, lastName, address, telephone, email) values (7, 'Netta', 'Offell', '868 Prairie Rose Point', '0984406310', 'noffell6@sciencedaily.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (8, 'Bertina', 'Borrel', '8077 Sunfield Crossing', '0967258043', 'bborrel7@dyndns.org');
insert into seller (idSeller, name, lastName, address, telephone, email) values (9, 'Lisetta', 'Eastwood', '7 Cherokee Way', '0926452959', 'leastwood8@com.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (10, 'Cob', 'Millhouse', '2 Packers Drive', '0996464020', 'cmillhouse9@hugedomains.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (11, 'Nisse', 'Burk', '32232 Waxwing Court', '0940784974', 'nburka@elegantthemes.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (12, 'Jean', 'Maydwell', '55711 Armistice Lane', '0980959124', 'jmaydwellb@people.com.cn');
insert into seller (idSeller, name, lastName, address, telephone, email) values (13, 'Corrine', 'Schreiner', '3 Westend Junction', '0953905247', 'cschreinerc@hp.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (14, 'Kimbell', 'Dunbleton', '250 Canary Trail', '0914616006', 'kdunbletond@loc.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (15, 'Barbaraanne', 'Grindlay', '91 Westerfield Lane', '0917340016', 'bgrindlaye@amazon.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (16, 'Hartley', 'McGavin', '816 Corben Terrace', '0981677140', 'hmcgavinf@ehow.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (17, 'Kristofer', 'Godehard.sf', '3074 Nova Court', '0920196091', 'kgodehardsfg@360.cn');
insert into seller (idSeller, name, lastName, address, telephone, email) values (18, 'Levi', 'Upfold', '43476 Ridgeway Parkway', '0932345329', 'lupfoldh@wordpress.org');
insert into seller (idSeller, name, lastName, address, telephone, email) values (19, 'Lucine', 'Hruska', '30872 Comanche Junction', '0939416667', 'lhruskai@joomla.org');
insert into seller (idSeller, name, lastName, address, telephone, email) values (20, 'Shane', 'Foran', '7061 Coleman Crossing', '0929782830', 'sforanj@mediafire.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (21, 'Phyllis', 'Hinstock', '471 Lyons Terrace', '0975998872', 'phinstockk@sakura.ne.jp');
insert into seller (idSeller, name, lastName, address, telephone, email) values (22, 'Annemarie', 'Duberry', '067 Buena Vista Trail', '0970166609', 'aduberryl@lycos.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (23, 'Donny', 'Cheshir', '64 Tomscot Place', '0986582197', 'dcheshirm@telegraph.co.uk');
insert into seller (idSeller, name, lastName, address, telephone, email) values (24, 'Elnore', 'Mitrovic', '6 Thompson Crossing', '0960392745', 'emitrovicn@shutterfly.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (25, 'Antin', 'Leavey', '4 Lien Center', '0932274467', 'aleaveyo@vinaora.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (26, 'Elsie', 'Symper', '42095 6th Avenue', '0909660004', 'esymperp@weebly.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (27, 'Willy', 'Manwell', '0117 Schiller Alley', '0958328241', 'wmanwellq@omniture.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (28, 'Nona', 'Letson', '733 Atwood Point', '0925054892', 'nletsonr@phpbb.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (29, 'Ber', 'Cushe', '70 Northwestern Pass', '0951706331', 'bcushes@soup.io');
insert into seller (idSeller, name, lastName, address, telephone, email) values (30, 'Ned', 'Deem', '51354 1st Point', '0923578376', 'ndeemt@disqus.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (31, 'Harv', 'Jerger', '4 Crescent Oaks Road', '0963461152', 'hjergeru@usnews.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (32, 'Rosanna', 'Jales', '06701 Macpherson Center', '0902668478', 'rjalesv@newyorker.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (33, 'Galina', 'Boycott', '30746 Nevada Parkway', '0920856875', 'gboycottw@va.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (34, 'Flora', 'Heams', '7 Mariners Cove Road', '0931481304', 'fheamsx@friendfeed.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (35, 'Konrad', 'Aslott', '524 Shelley Circle', '0908992135', 'kaslotty@usgs.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (36, 'Marylou', 'Elderfield', '6162 Darwin Drive', '0935655025', 'melderfieldz@epa.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (37, 'Cherice', 'Abernethy', '36137 Walton Plaza', '0916697671', 'cabernethy10@cnet.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (38, 'Evangeline', 'Baniard', '08 Kim Parkway', '0913802488', 'ebaniard11@arizona.edu');
insert into seller (idSeller, name, lastName, address, telephone, email) values (39, 'Corny', 'Comusso', '275 Moose Circle', '0904911780', 'ccomusso12@sakura.ne.jp');
insert into seller (idSeller, name, lastName, address, telephone, email) values (40, 'Marv', 'Coniff', '05112 Lakewood Gardens Terrace', '0937557902', 'mconiff13@qq.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (41, 'Cindee', 'Pollack', '398 Elgar Court', '0904896815', 'cpollack14@epa.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (42, 'Scotti', 'Brooks', '2435 Cardinal Drive', '0992526945', 'sbrooks15@jalbum.net');
insert into seller (idSeller, name, lastName, address, telephone, email) values (43, 'Thomasine', 'Timbridge', '07508 Kenwood Street', '0900183936', 'ttimbridge16@miitbeian.gov.cn');
insert into seller (idSeller, name, lastName, address, telephone, email) values (44, 'Bail', 'Skullet', '57786 Quincy Point', '0923218683', 'bskullet17@youtube.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (45, 'Revkah', 'Habbijam', '3 Gateway Alley', '0929954014', 'rhabbijam18@smh.com.au');
insert into seller (idSeller, name, lastName, address, telephone, email) values (46, 'Ericha', 'Denys', '899 Orin Park', '0935479532', 'edenys19@home.pl');
insert into seller (idSeller, name, lastName, address, telephone, email) values (47, 'Stanwood', 'Flemming', '3379 Saint Paul Court', '0912144765', 'sflemming1a@ebay.co.uk');
insert into seller (idSeller, name, lastName, address, telephone, email) values (48, 'Vi', 'Laurenty', '67557 Clarendon Terrace', '0923441287', 'vlaurenty1b@nasa.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (49, 'Killian', 'Armell', '854 Karstens Pass', '0995727567', 'karmell1c@t.co');
insert into seller (idSeller, name, lastName, address, telephone, email) values (50, 'Angelika', 'Robke', '2 Hoard Trail', '0956400597', 'arobke1d@vinaora.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (51, 'Torrey', 'Keelinge', '311 Sundown Junction', '0981154324', 'tkeelinge1e@washingtonpost.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (52, 'Vin', 'Avrahamof', '6 Leroy Road', '0901596752', 'vavrahamof1f@reddit.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (53, 'Brandtr', 'Marder', '703 Emmet Place', '0942226914', 'bmarder1g@hexun.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (54, 'Constantine', 'Agar', '58 Corben Pass', '0946180961', 'cagar1h@businessweek.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (55, 'Christa', 'Tillot', '16 Pawling Avenue', '0959108608', 'ctillot1i@washington.edu');
insert into seller (idSeller, name, lastName, address, telephone, email) values (56, 'Reagan', 'Bonnett', '05 Vahlen Crossing', '0941273979', 'rbonnett1j@technorati.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (57, 'Loren', 'Fawcus', '2 Chive Street', '0946868478', 'lfawcus1k@netscape.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (58, 'Betti', 'Bein', '981 Steensland Point', '0984492107', 'bbein1l@msn.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (59, 'Albina', 'Fentem', '3 Oneill Park', '0983488405', 'afentem1m@woothemes.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (60, 'Hephzibah', 'Gouth', '537 Summerview Trail', '0998607001', 'hgouth1n@godaddy.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (61, 'Pryce', 'Mackness', '454 Bellgrove Avenue', '0964730947', 'pmackness1o@chron.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (62, 'Shea', 'Baden', '62368 International Terrace', '0999309960', 'sbaden1p@paypal.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (63, 'Tina', 'Wyldbore', '82 Rutledge Point', '0922625884', 'twyldbore1q@theatlantic.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (64, 'Hally', 'Reedshaw', '65 Sheridan Court', '0969012512', 'hreedshaw1r@over-blog.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (65, 'Carissa', 'Kenway', '2066 Arapahoe Center', '0963726806', 'ckenway1s@ehow.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (66, 'Harper', 'Lorkins', '7 Clarendon Plaza', '0978404091', 'hlorkins1t@accuweather.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (67, 'Rice', 'Swatton', '305 Transport Park', '0972325889', 'rswatton1u@sbwire.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (68, 'Ilyssa', 'Van''t Hoff', '94 Hoard Street', '0966886190', 'ivanthoff1v@examiner.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (69, 'Helga', 'Halfacre', '1747 Heath Place', '0986902678', 'hhalfacre1w@elpais.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (70, 'Rodge', 'Oxburgh', '544 Caliangt Road', '0935814938', 'roxburgh1x@microsoft.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (71, 'Kay', 'Archbutt', '1 1st Pass', '0943437740', 'karchbutt1y@technorati.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (72, 'Danica', 'Baysting', '6547 Merry Park', '0907787985', 'dbaysting1z@sourceforge.net');
insert into seller (idSeller, name, lastName, address, telephone, email) values (73, 'Selestina', 'Fredson', '2 Norway Maple Pass', '0919554231', 'sfredson20@indiegogo.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (74, 'Pieter', 'Romaint', '56 American Terrace', '0929463797', 'promaint21@drupal.org');
insert into seller (idSeller, name, lastName, address, telephone, email) values (75, 'Nydia', 'Twatt', '396 Hanover Lane', '0951685225', 'ntwatt22@sbwire.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (76, 'Darcie', 'Harrower', '26989 Aberg Lane', '0965356259', 'dharrower23@liveinternet.ru');
insert into seller (idSeller, name, lastName, address, telephone, email) values (77, 'Jarrod', 'Heistermann', '3903 Atwood Drive', '0956533360', 'jheistermann24@privacy.gov.au');
insert into seller (idSeller, name, lastName, address, telephone, email) values (78, 'Doria', 'Aizikovitz', '5 Emmet Pass', '0912853318', 'daizikovitz25@soup.io');
insert into seller (idSeller, name, lastName, address, telephone, email) values (79, 'Em', 'Benham', '24992 Sycamore Plaza', '0951546741', 'ebenham26@omniture.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (80, 'Lyn', 'Crease', '04 Amoth Way', '0969190911', 'lcrease27@adobe.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (81, 'Claribel', 'Ludwell', '75141 Talmadge Hill', '0951932988', 'cludwell28@xing.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (82, 'Jocelyn', 'Guyton', '36410 Melody Junction', '0903451466', 'jguyton29@cnbc.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (83, 'Philip', 'Lionel', '52 Lakewood Gardens Road', '0938114758', 'plionel2a@topsy.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (84, 'Herve', 'Roome', '9406 Petterle Place', '0912180681', 'hroome2b@bravesites.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (85, 'Lyda', 'Ferenczy', '5 Jana Way', '0959452751', 'lferenczy2c@amazon.co.uk');
insert into seller (idSeller, name, lastName, address, telephone, email) values (86, 'Rayshell', 'Gantzer', '02424 Buena Vista Park', '0917511925', 'rgantzer2d@cdc.gov');
insert into seller (idSeller, name, lastName, address, telephone, email) values (87, 'Mace', 'Malling', '650 Stoughton Avenue', '0943074646', 'mmalling2e@instagram.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (88, 'Alys', 'Palle', '1 Green Ridge Crossing', '0977765319', 'apalle2f@aol.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (89, 'Pris', 'Searle', '691 Cottonwood Point', '0948654916', 'psearle2g@typepad.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (90, 'Pat', 'Romand', '3307 Ohio Plaza', '0938300041', 'promand2h@devhub.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (91, 'Vern', 'Vaugham', '1997 Kingsford Lane', '0954816414', 'vvaugham2i@opensource.org');
insert into seller (idSeller, name, lastName, address, telephone, email) values (92, 'Shela', 'McKeon', '80473 4th Hill', '0936051404', 'smckeon2j@indiegogo.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (93, 'Maurizia', 'Mobius', '39724 Nobel Plaza', '0915922149', 'mmobius2k@si.edu');
insert into seller (idSeller, name, lastName, address, telephone, email) values (94, 'Agretha', 'Buckmaster', '63626 Mayfield Road', '0923785952', 'abuckmaster2l@amazon.co.uk');
insert into seller (idSeller, name, lastName, address, telephone, email) values (95, 'Collie', 'O''Lyhane', '332 Golf View Parkway', '0961039422', 'colyhane2m@bandcamp.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (96, 'Angelia', 'Lamport', '614 Surrey Court', '0992128826', 'alamport2n@narod.ru');
insert into seller (idSeller, name, lastName, address, telephone, email) values (97, 'Sophi', 'Khristoforov', '6699 Hoffman Pass', '0946887086', 'skhristoforov2o@ycombinator.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (98, 'Keslie', 'Tibols', '533 Express Trail', '0984032793', 'ktibols2p@creativecommons.org');
insert into seller (idSeller, name, lastName, address, telephone, email) values (99, 'Cob', 'Hallagan', '85 Kropf Plaza', '0941111096', 'challagan2q@time.com');
insert into seller (idSeller, name, lastName, address, telephone, email) values (100, 'Henryetta', 'Medland', '366 International Place', '0961641887', 'hmedland2r@about.com');
